language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
env:
  - INJECTOR_VERSION=">=0.11,<0.12" FLASK_VERSION="==0.11"
  - INJECTOR_VERSION=">=0.12" FLASK_VERSION="==0.11"
  - INJECTOR_VERSION=">=0.11,<0.12" FLASK_VERSION=">0.11"
  - INJECTOR_VERSION=">=0.12" FLASK_VERSION=">0.11"
install:
  - pip install flake8 nose==1.3.0 flask$FLASK_VERSION flask_restful flask_restplus injector$INJECTOR_VERSION flask_cache flask_sqlalchemy eventlet typing mypy-lang typed_ast
script:
  - make test
